version : '2'
services:

  redis:
    image: redis:3
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
  nginx:
    build: nginx
    image: jo/nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx/dist/:/etc/nginx/html/
    links:
      - jsweb 

  mysql:
    build: mysql
    image: jo/mysql
    volumes:
           - ./src/main/docker/mysql/my.cnf:/root/mysql/my.cnf mysql
           - ./mysql/data:/var/lib/mysql:rw
    command: --max_allowed_packet=32505856
    environment:
       - MYSQL_ROOT_PASSWORD=123456
    ports:
       - "3306"
    expose:
       - "3306"

  jsweb:
    build: jsweb
    image: jo/jsweb
    volumes:
      - ./w.sh:/w.sh
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
      - redis
    entrypoint: "./w.sh mysql:3306 -- java -jar /app.jar"