package localhost.services.hrmservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-28T14:50:36.166+07:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://localhost/services/HrmService", name = "HrmServicePortType")
@XmlSeeAlso({weaver.hrm.webservice.ObjectFactory.class, ObjectFactory.class})
public interface HrmServicePortType {

    @WebMethod(operationName = "SynHrmResource")
    @RequestWrapper(localName = "SynHrmResource", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.SynHrmResource")
    @ResponseWrapper(localName = "SynHrmResourceResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.SynHrmResourceResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String synHrmResource(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1
    );

    @WebMethod
    @RequestWrapper(localName = "checkUser", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.CheckUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.CheckUserResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public boolean checkUser(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in2
    );

    @WebMethod
    @RequestWrapper(localName = "writeLog", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.WriteLog")
    @ResponseWrapper(localName = "writeLogResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.WriteLogResponse")
    public void writeLog(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.Object in0
    );

    @WebMethod
    @RequestWrapper(localName = "getHrmDepartmentInfo", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmDepartmentInfo")
    @ResponseWrapper(localName = "getHrmDepartmentInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmDepartmentInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public weaver.hrm.webservice.ArrayOfDepartmentBean getHrmDepartmentInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1
    );

    @WebMethod
    @RequestWrapper(localName = "getPropValue", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetPropValue")
    @ResponseWrapper(localName = "getPropValueResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetPropValueResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String getPropValue(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1
    );

    @WebMethod
    @RequestWrapper(localName = "getHrmSubcompanyInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmSubcompanyInfoXML")
    @ResponseWrapper(localName = "getHrmSubcompanyInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmSubcompanyInfoXMLResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String getHrmSubcompanyInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "getHrmUserInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmUserInfoXML")
    @ResponseWrapper(localName = "getHrmUserInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmUserInfoXMLResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String getHrmUserInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in5
    );

    @WebMethod(operationName = "SynJobtitle")
    @RequestWrapper(localName = "SynJobtitle", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.SynJobtitle")
    @ResponseWrapper(localName = "SynJobtitleResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.SynJobtitleResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String synJobtitle(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1
    );

    @WebMethod
    @RequestWrapper(localName = "getHrmDepartmentInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmDepartmentInfoXML")
    @ResponseWrapper(localName = "getHrmDepartmentInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmDepartmentInfoXMLResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String getHrmDepartmentInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1
    );

    @WebMethod
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.ChangeUserPasswordResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public boolean changeUserPassword(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in2
    );

    @WebMethod
    @RequestWrapper(localName = "getHrmJobTitleInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmJobTitleInfoXML")
    @ResponseWrapper(localName = "getHrmJobTitleInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmJobTitleInfoXMLResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String getHrmJobTitleInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in2
    );

    @WebMethod
    @RequestWrapper(localName = "getClientIpXfire", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetClientIpXfire")
    @ResponseWrapper(localName = "getClientIpXfireResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetClientIpXfireResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String getClientIpXfire();

    @WebMethod(operationName = "SynSubCompany")
    @RequestWrapper(localName = "SynSubCompany", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.SynSubCompany")
    @ResponseWrapper(localName = "SynSubCompanyResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.SynSubCompanyResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String synSubCompany(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1
    );

    @WebMethod
    @RequestWrapper(localName = "getHrmJobTitleInfo", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmJobTitleInfo")
    @ResponseWrapper(localName = "getHrmJobTitleInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmJobTitleInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public weaver.hrm.webservice.ArrayOfJobTitleBean getHrmJobTitleInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in2
    );

    @WebMethod(operationName = "LoadTemplateProp")
    @RequestWrapper(localName = "LoadTemplateProp", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.LoadTemplateProp")
    @ResponseWrapper(localName = "LoadTemplatePropResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.LoadTemplatePropResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public localhost.services.hrmservice.AnyType2AnyTypeMap loadTemplateProp(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "writeLog1", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.WriteLog1")
    @ResponseWrapper(localName = "writeLog1Response", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.WriteLog1Response")
    public void writeLog1(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.Object in1
    );

    @WebMethod
    @RequestWrapper(localName = "getHrmSubcompanyInfo", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmSubcompanyInfo")
    @ResponseWrapper(localName = "getHrmSubcompanyInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmSubcompanyInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public weaver.hrm.webservice.ArrayOfSubCompanyBean getHrmSubcompanyInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "getHrmUserInfo", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmUserInfo")
    @ResponseWrapper(localName = "getHrmUserInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.GetHrmUserInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public weaver.hrm.webservice.ArrayOfUserBean getHrmUserInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in5
    );

    @WebMethod(operationName = "SynDepartment")
    @RequestWrapper(localName = "SynDepartment", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.SynDepartment")
    @ResponseWrapper(localName = "SynDepartmentResponse", targetNamespace = "http://localhost/services/HrmService", className = "localhost.services.hrmservice.SynDepartmentResponse")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    public java.lang.String synDepartment(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        java.lang.String in1
    );
}
