
package localhost.services.hrmservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-09-28T14:50:36.119+07:00
 * Generated source version: 3.0.16
 * 
 */
public final class HrmServicePortType_HrmServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://localhost/services/HrmService", "HrmService");

    private HrmServicePortType_HrmServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HrmService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HrmService ss = new HrmService(wsdlURL, SERVICE_NAME);
        HrmServicePortType port = ss.getHrmServiceHttpPort();  
        
        {
        System.out.println("Invoking synHrmResource...");
        java.lang.String _synHrmResource_in0 = "";
        java.lang.String _synHrmResource_in1 = "";
        java.lang.String _synHrmResource__return = port.synHrmResource(_synHrmResource_in0, _synHrmResource_in1);
        System.out.println("synHrmResource.result=" + _synHrmResource__return);


        }
        {
        System.out.println("Invoking checkUser...");
        java.lang.String _checkUser_in0 = "";
        java.lang.String _checkUser_in1 = "";
        java.lang.String _checkUser_in2 = "";
        boolean _checkUser__return = port.checkUser(_checkUser_in0, _checkUser_in1, _checkUser_in2);
        System.out.println("checkUser.result=" + _checkUser__return);


        }
        {
        System.out.println("Invoking writeLog...");
        java.lang.Object _writeLog_in0 = new java.lang.Object();
        port.writeLog(_writeLog_in0);


        }
        {
        System.out.println("Invoking getHrmDepartmentInfo...");
        java.lang.String _getHrmDepartmentInfo_in0 = "";
        java.lang.String _getHrmDepartmentInfo_in1 = "";
        weaver.hrm.webservice.ArrayOfDepartmentBean _getHrmDepartmentInfo__return = port.getHrmDepartmentInfo(_getHrmDepartmentInfo_in0, _getHrmDepartmentInfo_in1);
        System.out.println("getHrmDepartmentInfo.result=" + _getHrmDepartmentInfo__return);


        }
        {
        System.out.println("Invoking getPropValue...");
        java.lang.String _getPropValue_in0 = "";
        java.lang.String _getPropValue_in1 = "";
        java.lang.String _getPropValue__return = port.getPropValue(_getPropValue_in0, _getPropValue_in1);
        System.out.println("getPropValue.result=" + _getPropValue__return);


        }
        {
        System.out.println("Invoking getHrmSubcompanyInfoXML...");
        java.lang.String _getHrmSubcompanyInfoXML_in0 = "";
        java.lang.String _getHrmSubcompanyInfoXML__return = port.getHrmSubcompanyInfoXML(_getHrmSubcompanyInfoXML_in0);
        System.out.println("getHrmSubcompanyInfoXML.result=" + _getHrmSubcompanyInfoXML__return);


        }
        {
        System.out.println("Invoking getHrmUserInfoXML...");
        java.lang.String _getHrmUserInfoXML_in0 = "";
        java.lang.String _getHrmUserInfoXML_in1 = "";
        java.lang.String _getHrmUserInfoXML_in2 = "";
        java.lang.String _getHrmUserInfoXML_in3 = "";
        java.lang.String _getHrmUserInfoXML_in4 = "";
        java.lang.String _getHrmUserInfoXML_in5 = "";
        java.lang.String _getHrmUserInfoXML__return = port.getHrmUserInfoXML(_getHrmUserInfoXML_in0, _getHrmUserInfoXML_in1, _getHrmUserInfoXML_in2, _getHrmUserInfoXML_in3, _getHrmUserInfoXML_in4, _getHrmUserInfoXML_in5);
        System.out.println("getHrmUserInfoXML.result=" + _getHrmUserInfoXML__return);


        }
        {
        System.out.println("Invoking synJobtitle...");
        java.lang.String _synJobtitle_in0 = "";
        java.lang.String _synJobtitle_in1 = "";
        java.lang.String _synJobtitle__return = port.synJobtitle(_synJobtitle_in0, _synJobtitle_in1);
        System.out.println("synJobtitle.result=" + _synJobtitle__return);


        }
        {
        System.out.println("Invoking getHrmDepartmentInfoXML...");
        java.lang.String _getHrmDepartmentInfoXML_in0 = "";
        java.lang.String _getHrmDepartmentInfoXML_in1 = "";
        java.lang.String _getHrmDepartmentInfoXML__return = port.getHrmDepartmentInfoXML(_getHrmDepartmentInfoXML_in0, _getHrmDepartmentInfoXML_in1);
        System.out.println("getHrmDepartmentInfoXML.result=" + _getHrmDepartmentInfoXML__return);


        }
        {
        System.out.println("Invoking changeUserPassword...");
        java.lang.String _changeUserPassword_in0 = "";
        java.lang.String _changeUserPassword_in1 = "";
        java.lang.String _changeUserPassword_in2 = "";
        boolean _changeUserPassword__return = port.changeUserPassword(_changeUserPassword_in0, _changeUserPassword_in1, _changeUserPassword_in2);
        System.out.println("changeUserPassword.result=" + _changeUserPassword__return);


        }
        {
        System.out.println("Invoking getHrmJobTitleInfoXML...");
        java.lang.String _getHrmJobTitleInfoXML_in0 = "";
        java.lang.String _getHrmJobTitleInfoXML_in1 = "";
        java.lang.String _getHrmJobTitleInfoXML_in2 = "";
        java.lang.String _getHrmJobTitleInfoXML__return = port.getHrmJobTitleInfoXML(_getHrmJobTitleInfoXML_in0, _getHrmJobTitleInfoXML_in1, _getHrmJobTitleInfoXML_in2);
        System.out.println("getHrmJobTitleInfoXML.result=" + _getHrmJobTitleInfoXML__return);


        }
        {
        System.out.println("Invoking getClientIpXfire...");
        java.lang.String _getClientIpXfire__return = port.getClientIpXfire();
        System.out.println("getClientIpXfire.result=" + _getClientIpXfire__return);


        }
        {
        System.out.println("Invoking synSubCompany...");
        java.lang.String _synSubCompany_in0 = "";
        java.lang.String _synSubCompany_in1 = "";
        java.lang.String _synSubCompany__return = port.synSubCompany(_synSubCompany_in0, _synSubCompany_in1);
        System.out.println("synSubCompany.result=" + _synSubCompany__return);


        }
        {
        System.out.println("Invoking getHrmJobTitleInfo...");
        java.lang.String _getHrmJobTitleInfo_in0 = "";
        java.lang.String _getHrmJobTitleInfo_in1 = "";
        java.lang.String _getHrmJobTitleInfo_in2 = "";
        weaver.hrm.webservice.ArrayOfJobTitleBean _getHrmJobTitleInfo__return = port.getHrmJobTitleInfo(_getHrmJobTitleInfo_in0, _getHrmJobTitleInfo_in1, _getHrmJobTitleInfo_in2);
        System.out.println("getHrmJobTitleInfo.result=" + _getHrmJobTitleInfo__return);


        }
        {
        System.out.println("Invoking loadTemplateProp...");
        java.lang.String _loadTemplateProp_in0 = "";
        localhost.services.hrmservice.AnyType2AnyTypeMap _loadTemplateProp__return = port.loadTemplateProp(_loadTemplateProp_in0);
        System.out.println("loadTemplateProp.result=" + _loadTemplateProp__return);


        }
        {
        System.out.println("Invoking writeLog1...");
        java.lang.String _writeLog1_in0 = "";
        java.lang.Object _writeLog1_in1 = new java.lang.Object();
        port.writeLog1(_writeLog1_in0, _writeLog1_in1);


        }
        {
        System.out.println("Invoking getHrmSubcompanyInfo...");
        java.lang.String _getHrmSubcompanyInfo_in0 = "";
        weaver.hrm.webservice.ArrayOfSubCompanyBean _getHrmSubcompanyInfo__return = port.getHrmSubcompanyInfo(_getHrmSubcompanyInfo_in0);
        System.out.println("getHrmSubcompanyInfo.result=" + _getHrmSubcompanyInfo__return);


        }
        {
        System.out.println("Invoking getHrmUserInfo...");
        java.lang.String _getHrmUserInfo_in0 = "";
        java.lang.String _getHrmUserInfo_in1 = "";
        java.lang.String _getHrmUserInfo_in2 = "";
        java.lang.String _getHrmUserInfo_in3 = "";
        java.lang.String _getHrmUserInfo_in4 = "";
        java.lang.String _getHrmUserInfo_in5 = "";
        weaver.hrm.webservice.ArrayOfUserBean _getHrmUserInfo__return = port.getHrmUserInfo(_getHrmUserInfo_in0, _getHrmUserInfo_in1, _getHrmUserInfo_in2, _getHrmUserInfo_in3, _getHrmUserInfo_in4, _getHrmUserInfo_in5);
        System.out.println("getHrmUserInfo.result=" + _getHrmUserInfo__return);


        }
        {
        System.out.println("Invoking synDepartment...");
        java.lang.String _synDepartment_in0 = "";
        java.lang.String _synDepartment_in1 = "";
        java.lang.String _synDepartment__return = port.synDepartment(_synDepartment_in0, _synDepartment_in1);
        System.out.println("synDepartment.result=" + _synDepartment__return);


        }

        System.exit(0);
    }

}
