server:
  port: 8090
  context-path: /jsweb
  tomcat:
    uri-encoding: UTF-8

spring:
  main: 
    banner-mode: "off"

shiro: 
  filterChainDefinitions: 
    ${adminPath}/third/** = anon

# Redis 配置（2.x/3.x）
#redis:
#  enabled: true
#  host: localhost
#  port: 6379
#  database: 0
#  password: 1234
#  pool:
#    maxIdle: 3
#    maxTotal: 20

#jdbc: #开发本地
#  type: mysql
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/mypro?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#  username: root
#  password: root
#  testSql: SELECT 1



jdbc: #阿里云
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://rm-j6cm70w513grj0w24lo.mysql.rds.aliyuncs.com:3306/js?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
  username: root
  password: Zxc**123
  testSql: SELECT 1

#jdbc: #docker
#  type: mysql
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql://mysql:3306/js?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
#  username: docker
#  password: root
#  testSql: SELECT 1
redis:
  enabled: true
  host: redis
  port: 6379
  database: 0
  password: 1234
  pool:
    maxIdle: 3
    maxTotal: 20
