spring: 
  profiles: local

# Redis 配置（2.x/3.x）
redis:
  enabled: true
  host: localhost
  port: 6379
  database: 0
  password: 1234
  pool:
    maxIdle: 3
    maxTotal: 20

jdbc: 
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/mypro?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
  username: root
  password: root
  testSql: SELECT 1
  
file:
  # 上传单个文件最大字节（500M），在这之上还有 > Tomcat限制 > Nginx限制，等。
  maxFileSize: 500*1024*1024
  baseDir: /Users/linwei/logs/upload
  uploadPath: '{yyyy}{MM}/'