version : '2'
services:

  redis:
    image: redis:3
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
  nginx:
    build: nginx
    image: jo/nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx/dist/:/etc/nginx/html/
    links:
      - jsweb

  jsweb:
    image: zxx267/jsweb
    ports:
      - "8090:8090"
    restart: always
    links:
      - redis
